apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ay28lmksm-go
  janus-idp.io/tekton: ay28lmksm-go
  backstage.io/kubernetes-id: ay28lmksm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ay28lmksm-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
