apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ay28lmksm-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ay28lmksm-go 
  name: ay28lmksm-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ay28lmksm-go 
